export type {
  Status, ProgramItem, Todo, BudgetLineItem, BudgetCategory,
  TimelineItem, EventBriefing, Event,
} from "./types";

import type { Event } from "./types";

export const events: Event[] = [
  {
    id: 1,
    name: "Strategie Offsite — Q3 Leadership",
    date: "12 juni 2025",
    startTime: "10:00",
    endTime: "18:00",
    location: "Het Scheepvaartmuseum, Amsterdam",
    guests: 34,
    status: "bevestigd",
    type: "Corporate Retreat",
    coverColor: "#e86fa3",
    totalBudget: 10350,
    briefing: {
      concept: "Een volledige dag buiten de kantooromgeving voor het leadership team. Focus op strategie Q3/Q4, teamcohesie en besluitvorming. Rustige, geconcentreerde sfeer met ruimte voor verdieping.",
      doelgroep: "34 directeuren en senior managers",
      sfeerThema: "Focus & Richting — weg van de waan van de dag",
      format: "Plenaire sessies afgewisseld met groepsworkshops, lunch met vrije tafelindeling, afsluiting met borrel",
      bijzonderheden: "",
      dresscode: "Smart casual",
      cateringWensen: "Lunch buffet, doorlopende koffie & thee, borrelsnacks vanaf 17:45",
      avTechniek: "Beamer, draadloze microfoon, flip-overs per breakoutruimte",
      vrijeNotities: "",
    },
    program: [
      { time: "09:30", title: "Inloop & koffie" },
      { time: "10:00", title: "Opening door CEO", notes: "Max 20 min, toon zetten" },
      { time: "10:30", title: "Plenaire sessie: Terugblik H1" },
      { time: "12:00", title: "Lunch (buffet, vrije opstelling)" },
      { time: "13:00", title: "Groepsworkshops (3x parallel)", notes: "Ruimte A, B en C" },
      { time: "15:00", title: "Pauze & bewegingsmoment" },
      { time: "15:30", title: "Plenaire terugkoppeling workshops" },
      { time: "17:00", title: "Besluitvorming & prioriteiten Q3" },
      { time: "17:45", title: "Afsluiting & borrel" },
    ],
    todos: [
      { id: 1, text: "Offerte catering bevestigen", status: "done", deadline: "15 mei", category: "Catering" },
      { id: 2, text: "AV-setup controleren met venue", status: "done", deadline: "1 juni", category: "Locatie" },
      { id: 3, text: "Programmaboekje naar drukker", status: "open", deadline: "5 juni", category: "Communicatie" },
      { id: 4, text: "Reisinfo sturen naar deelnemers", status: "open", deadline: "5 juni", category: "Communicatie" },
      { id: 5, text: "Workshopmateriaal ophalen", status: "open", deadline: "11 juni", category: "Inhoud" },
      { id: 6, text: "Naam badges bestellen", status: "open", deadline: "8 juni", category: "Logistiek" },
      { id: 7, text: "Parkeerfaciliteiten regelen", status: "open", deadline: "10 juni", category: "Logistiek" },
    ],
    budgetCategories: [
      {
        id: 1,
        name: "Locatiehuur",
        items: [{ id: 1, description: "Zaalkosten dagdeel", amountExclVat: 3719, vatRate: 21 }],
      },
      {
        id: 2,
        name: "Catering",
        items: [
          { id: 1, description: "Lunch buffet (34 pers)", amountExclVat: 1488, vatRate: 9 },
          { id: 2, description: "Borrelsnacks & drankjes", amountExclVat: 1033, vatRate: 9 },
        ],
      },
      {
        id: 3,
        name: "AV & techniek",
        items: [{ id: 1, description: "Technicus + materiaal", amountExclVat: 1157, vatRate: 21 }],
      },
      {
        id: 4,
        name: "Drukwerk",
        items: [{ id: 1, description: "Programmaboekjes", amountExclVat: 289, vatRate: 21 }],
      },
      {
        id: 5,
        name: "Overig",
        items: [{ id: 1, description: "Naam badges & materiaal", amountExclVat: 99, vatRate: 21 }],
      },
    ],
    timeline: [
      { id: 1, date: "1 apr", title: "Locatie geboekt", done: true, type: "user" },
      { id: 2, date: "15 apr", title: "Programma vastgesteld", done: true, type: "user" },
      { id: 3, date: "1 mei", title: "Uitnodigingen verstuurd", done: true, type: "user" },
      { id: 4, date: "15 mei", title: "Catering bevestigd", done: true, type: "user" },
      { id: 5, date: "5 jun", title: "Programmaboekje klaar", done: false, type: "user", linkedTodoId: 3 },
      { id: 6, date: "5 jun", title: "Reisinfo verstuurd", done: false, type: "user", linkedTodoId: 4 },
      { id: 7, date: "10 jun", title: "Alle logistiek geregeld", done: false, type: "user" },
      { id: 8, date: "12 jun", title: "Event", done: false, type: "user" },
    ],
  },
  {
    id: 2,
    name: "Zomerborrel Tech & Talent",
    date: "27 juni 2025",
    startTime: "17:00",
    endTime: "21:00",
    location: "Rooftop NDSM, Amsterdam-Noord",
    guests: 120,
    status: "in voorbereiding",
    type: "Netwerkevent",
    coverColor: "#6e9fc8",
    totalBudget: 8600,
    briefing: {
      concept: "Informele zomerborrel voor relaties en medewerkers uit de tech- en talentenbranche. Luchtige sfeer, rooftop met uitzicht, muziek op de achtergrond.",
      doelgroep: "120 professionals (mix klanten, partners en interne collega's)",
      sfeerThema: "Zomer / open lucht / verbinding",
      format: "Staande receptie, geen programma, DJ set, bites & drinks",
      bijzonderheden: "Regenplan nodig — tent of alternatieve locatie binnenshuis.",
      dresscode: "Casual zomer",
      cateringWensen: "Bites in twee rondes, open bar met wijn/bier/frisdrank",
      avTechniek: "DJ setup met eigen geluidsinstallatie",
      vrijeNotities: "",
    },
    program: [
      { time: "17:00", title: "Deuren open, welkomstdrankje" },
      { time: "17:30", title: "DJ start", notes: "Relaxed background set" },
      { time: "19:00", title: "Bites ronde 2" },
      { time: "20:30", title: "Last orders" },
      { time: "21:00", title: "Einde officieel programma" },
    ],
    todos: [
      { id: 1, text: "Regenplan bevestigen met venue", status: "open", deadline: "10 jun", category: "Locatie" },
      { id: 2, text: "DJ contract tekenen", status: "open", deadline: "1 jun", category: "Entertainment" },
      { id: 3, text: "Uitnodigingen sturen (2e ronde)", status: "open", deadline: "15 jun", category: "Communicatie" },
      { id: 4, text: "Barmedewerkers boeken", status: "open", deadline: "1 jun", category: "Catering" },
      { id: 5, text: "RSVP-deadline bewaken", status: "open", deadline: "20 jun", category: "Gasten" },
    ],
    budgetCategories: [
      {
        id: 1,
        name: "Locatiehuur",
        items: [{ id: 1, description: "Rooftop dagdeel", amountExclVat: 2314, vatRate: 21 }],
      },
      {
        id: 2,
        name: "Catering & bar",
        items: [
          { id: 1, description: "Bites & hapjes (120 pers)", amountExclVat: 2202, vatRate: 9 },
          { id: 2, description: "Drankenpakket", amountExclVat: 1651, vatRate: 9 },
        ],
      },
      {
        id: 3,
        name: "DJ & entertainment",
        items: [{ id: 1, description: "DJ set (4 uur)", amountExclVat: 744, vatRate: 21 }],
      },
      {
        id: 4,
        name: "Overig",
        items: [{ id: 1, description: "Decoratie & styling", amountExclVat: 248, vatRate: 21 }],
      },
    ],
    timeline: [
      { id: 1, date: "1 mei", title: "Locatie geboekt", done: true, type: "user" },
      { id: 2, date: "15 mei", title: "Uitnodigingen (1e ronde)", done: true, type: "user" },
      { id: 3, date: "1 jun", title: "DJ bevestigd", done: false, type: "user", linkedTodoId: 2 },
      { id: 4, date: "15 jun", title: "2e ronde uitnodigingen", done: false, type: "user", linkedTodoId: 3 },
      { id: 5, date: "20 jun", title: "RSVP-deadline", done: false, type: "user" },
      { id: 6, date: "25 jun", title: "Definitief gastenaantal door", done: false, type: "user" },
      { id: 7, date: "27 jun", title: "Event", done: false, type: "user" },
    ],
  },
  {
    id: 3,
    name: "Jaarlijks Klantendiner 2025",
    date: "18 september 2025",
    startTime: "19:00",
    endTime: "23:00",
    location: "Restaurant De Kas, Amsterdam",
    guests: 48,
    status: "concept",
    type: "Corporate Dinner",
    coverColor: "#a96ec8",
    totalBudget: 12800,
    briefing: {
      concept: "",
      doelgroep: "48 vaste klanten (A-relaties)",
      sfeerThema: "Nog te bepalen",
      format: "Zittend diner, meerdere gangen, korte toespraak directie",
      bijzonderheden: "",
      dresscode: "",
      cateringWensen: "",
      avTechniek: "",
      vrijeNotities: "",
    },
    program: [],
    todos: [
      { id: 1, text: "Locaties vergelijken en keuze maken", status: "open", deadline: "1 jul", category: "Locatie" },
      { id: 2, text: "Concept en thema uitwerken", status: "open", deadline: "1 jul", category: "Inhoud" },
    ],
    budgetCategories: [
      {
        id: 1,
        name: "Locatie & diner",
        items: [{ id: 1, description: "Locatiehuur + menu per persoon", amountExclVat: 7934, vatRate: 9 }],
      },
      {
        id: 2,
        name: "Wijn & dranken",
        items: [{ id: 1, description: "Wijnpakket + dranken", amountExclVat: 2202, vatRate: 9 }],
      },
      {
        id: 3,
        name: "Decoratie",
        items: [{ id: 1, description: "Tafelschikking & bloemen", amountExclVat: 661, vatRate: 21 }],
      },
    ],
    timeline: [
      { id: 1, date: "1 jul", title: "Locatie en concept vastgesteld", done: false, type: "user" },
      { id: 2, date: "1 aug", title: "Uitnodigingen verstuurd", done: false, type: "user" },
      { id: 3, date: "18 sep", title: "Event", done: false, type: "user" },
    ],
  },
  {
    id: 4,
    name: "Productlancering 'Nova'",
    date: "4 oktober 2025",
    startTime: "14:00",
    endTime: "20:00",
    location: "Westergasfabriek, Amsterdam",
    guests: 280,
    status: "in voorbereiding",
    type: "Lancering",
    coverColor: "#c86e6e",
    totalBudget: 48900,
    briefing: {
      concept: "Grootschalige lancering van product Nova voor pers, partners en klanten. Hoog energieniveau, indrukwekkende presentatie, feestelijk slot.",
      doelgroep: "Pers (40), partners (100), klanten (140)",
      sfeerThema: "Nova — nieuw tijdperk",
      format: "Presentatie, demo-stands, netwerkreceptie",
      bijzonderheden: "",
      dresscode: "Business",
      cateringWensen: "Receptie canapés, open bar tijdens netwerk",
      avTechniek: "LED wall, 5.1 surroundsound, 3 demo-stands met tablets",
      vrijeNotities: "",
    },
    program: [
      { time: "14:00", title: "Inloop & registratie" },
      { time: "15:00", title: "Plenaire presentatie (CEO + product team)" },
      { time: "16:30", title: "Product demo sessies (3 tracks)" },
      { time: "18:00", title: "Lanceringsmoment + toast" },
      { time: "18:30", title: "Netwerkreceptie" },
      { time: "20:00", title: "Einde" },
    ],
    todos: [
      { id: 1, text: "Persuitnodigingen versturen", status: "open", deadline: "1 aug", category: "PR" },
      { id: 2, text: "Presentatie CEO afstemmen", status: "open", deadline: "1 sep", category: "Inhoud" },
      { id: 3, text: "Demo-stands ontwerpen", status: "open", deadline: "15 aug", category: "Productie" },
      { id: 4, text: "Catering offerte aanvragen", status: "open", deadline: "1 jul", category: "Catering" },
    ],
    budgetCategories: [
      {
        id: 1,
        name: "Locatiehuur",
        items: [{ id: 1, description: "Westergasfabriek dagdeel", amountExclVat: 9917, vatRate: 21 }],
      },
      {
        id: 2,
        name: "Productie & stands",
        items: [
          { id: 1, description: "Demo-stands (3 stuks)", amountExclVat: 8264, vatRate: 21 },
          { id: 2, description: "Scenografie & decor", amountExclVat: 6612, vatRate: 21 },
        ],
      },
      {
        id: 3,
        name: "Catering",
        items: [{ id: 1, description: "Canapés + open bar (280 pers)", amountExclVat: 6936, vatRate: 9 }],
      },
      {
        id: 4,
        name: "AV & licht",
        items: [{ id: 1, description: "LED wall, geluid, belichting", amountExclVat: 5372, vatRate: 21 }],
      },
      {
        id: 5,
        name: "PR & communicatie",
        items: [{ id: 1, description: "Persberichten & uitnodigingen", amountExclVat: 3306, vatRate: 21 }],
      },
    ],
    timeline: [
      { id: 1, date: "1 jun", title: "Locatie geboekt", done: true, type: "user" },
      { id: 2, date: "1 jul", title: "Catering offerte aangevraagd", done: false, type: "user", linkedTodoId: 4 },
      { id: 3, date: "1 aug", title: "Persuitnodigingen verstuurd", done: false, type: "user", linkedTodoId: 1 },
      { id: 4, date: "15 aug", title: "Demo-stands ontworpen", done: false, type: "user", linkedTodoId: 3 },
      { id: 5, date: "1 sep", title: "Presentatie afgerond", done: false, type: "user", linkedTodoId: 2 },
      { id: 6, date: "4 okt", title: "Event", done: false, type: "user" },
    ],
  },
  {
    id: 5,
    name: "Team Retreat — Winter Edition",
    date: "5 december 2025",
    startTime: "10:00",
    endTime: "16:00",
    location: "Landgoed De Witte Berken, Drenthe",
    guests: 22,
    status: "concept",
    type: "Team Retreat",
    coverColor: "#6ec8b4",
    totalBudget: 5600,
    briefing: {
      concept: "",
      doelgroep: "22 teamleden",
      sfeerThema: "Nog te bepalen",
      format: "Dagprogramma met activiteiten en diner",
      bijzonderheden: "",
      dresscode: "",
      cateringWensen: "",
      avTechniek: "",
      vrijeNotities: "",
    },
    program: [],
    todos: [
      { id: 1, text: "Datum en locatie intern bevestigen", status: "open", deadline: "1 sep", category: "Logistiek" },
    ],
    budgetCategories: [
      {
        id: 1,
        name: "Locatie & accommodatie",
        items: [{ id: 1, description: "Landgoed daggebruik", amountExclVat: 2727, vatRate: 21 }],
      },
      {
        id: 2,
        name: "Activiteiten",
        items: [{ id: 1, description: "Teamactiviteiten", amountExclVat: 992, vatRate: 21 }],
      },
      {
        id: 3,
        name: "Catering",
        items: [{ id: 1, description: "Lunch + diner (22 pers)", amountExclVat: 917, vatRate: 9 }],
      },
    ],
    timeline: [
      { id: 1, date: "1 sep", title: "Locatie bevestigd", done: false, type: "user" },
      { id: 2, date: "5 dec", title: "Event", done: false, type: "user" },
    ],
  },
  {
    id: 6,
    name: "Nieuwjaarsreceptie 2025",
    date: "10 januari 2025",
    startTime: "16:00",
    endTime: "19:00",
    location: "Stadsschouwburg, Amsterdam",
    guests: 195,
    status: "afgerond",
    type: "Receptie",
    coverColor: "#8b8a7a",
    totalBudget: 14000,
    briefing: {
      concept: "Jaarlijkse nieuwjaarsreceptie voor relaties en medewerkers. Toespraak directie, buffet, netwerken.",
      doelgroep: "195 relaties en medewerkers",
      sfeerThema: "Nieuw jaar, nieuwe kansen",
      format: "Staande receptie, toespraak, buffet",
      bijzonderheden: "Parkeren was knelpunt — voor volgend jaar alternatief zoeken.",
      dresscode: "Smart casual",
      cateringWensen: "Warm & koud buffet, wijn & bier, frisdrank",
      avTechniek: "Microfoon voor toespraak, achtergrondmuziek",
      vrijeNotities: "Goed verlopen. Catering was uitstekend.",
    },
    program: [
      { time: "16:00", title: "Inloop" },
      { time: "16:30", title: "Toespraak directie" },
      { time: "17:00", title: "Buffet open" },
      { time: "19:00", title: "Einde" },
    ],
    todos: [],
    budgetCategories: [
      {
        id: 1,
        name: "Locatiehuur",
        items: [{ id: 1, description: "Stadsschouwburg zaal", amountExclVat: 3967, vatRate: 21 }],
      },
      {
        id: 2,
        name: "Catering",
        items: [{ id: 1, description: "Buffet + dranken (195 pers)", amountExclVat: 6789, vatRate: 9 }],
      },
      {
        id: 3,
        name: "AV",
        items: [{ id: 1, description: "Geluid & microfoon", amountExclVat: 620, vatRate: 21 }],
      },
      {
        id: 4,
        name: "Overig",
        items: [{ id: 1, description: "Diversen", amountExclVat: 256, vatRate: 21 }],
      },
    ],
    timeline: [
      { id: 1, date: "1 nov", title: "Locatie geboekt", done: true, type: "user" },
      { id: 2, date: "1 dec", title: "Uitnodigingen verstuurd", done: true, type: "user" },
      { id: 3, date: "10 jan", title: "Event", done: true, type: "user" },
    ],
  },
];
