export type {
  Status, ProgramItem, Todo, BudgetLineItem, BudgetCategory,
  TimelineItem, EventBriefing, Event, Supplier,
} from "./types";

import type { Event, Supplier } from "./types";

export const events: Event[] = [
  {
    id: 1,
    name: "North Sea Infrastructure",
    date: "15 september 2025",
    startTime: "15:00",
    endTime: "19:00",
    location: "Nader te bepalen",
    guests: 100,
    status: "concept",
    type: "Conferentie",
    coverColor: "#3d6e9e",
    totalBudget: 10000,
    briefing: {
      concept: "",
      doelgroep: "100 professionals uit infrastructuur, havens en maritieme sector",
      sfeerThema: "",
      format: "Presentaties, paneldiscussie, netwerkmogelijkheid",
      bijzonderheden: "",
      dresscode: "",
      cateringWensen: "",
      avTechniek: "",
      vrijeNotities: "",
    },
    program: [],
    todos: [],
    budgetCategories: [
      { id: 1, name: "Locatiehuur", items: [] },
      { id: 2, name: "Sprekers & honoraria", items: [] },
      { id: 3, name: "Catering", items: [] },
      { id: 4, name: "AV & techniek", items: [] },
    ],
    timeline: [
      { id: 1, date: "15 sep", title: "North Sea Infrastructure", done: false, type: "user" },
    ],
    noteWindows: [],
  },

  {
    id: 2,
    name: "Zeilevent Vastgoed",
    date: "17 september 2025",
    startTime: "14:00",
    endTime: "19:00",
    location: "Jachthaven Enkhuizen, Enkhuizen",
    guests: 100,
    status: "in voorbereiding",
    type: "Zeilevent",
    coverColor: "#4f8cc9",
    totalBudget: 12000,
    briefing: {
      concept: "",
      doelgroep: "100 vastgoedprofessionals (klanten & relaties)",
      sfeerThema: "Actief, verbindend, op het water",
      format: "Zeilen in teams, gevolgd door borrel op de kade",
      bijzonderheden: "",
      dresscode: "Nautisch casual — zeilschoenen aanbevolen",
      cateringWensen: "",
      avTechniek: "",
      vrijeNotities: "",
    },
    program: [],
    todos: [],
    budgetCategories: [
      { id: 1, name: "Bootenverhuur", items: [] },
      { id: 2, name: "Catering & borrel", items: [] },
      { id: 3, name: "Instructeurs", items: [] },
      { id: 4, name: "Overig", items: [] },
    ],
    timeline: [
      { id: 1, date: "17 sep", title: "Zeilevent Vastgoed", done: false, type: "user" },
    ],
    noteWindows: [],
  },

  {
    id: 3,
    name: "Vitaliteitsweek",
    date: "21–25 september 2025",
    startTime: "09:00",
    endTime: "17:00",
    location: "Kantoor",
    guests: 50,
    status: "in voorbereiding",
    type: "Vitaliteitsweek",
    coverColor: "#6dc88a",
    totalBudget: 8500,
    briefing: {
      concept: "5-daags programma rondom vitaliteit, beweging en mentale gezondheid op de werkvloer. Elke dag een ander thema.",
      doelgroep: "Alle medewerkers, circa 50 personen",
      sfeerThema: "Energie, gezondheid, verbinding",
      format: "Dagelijkse sessies van 45–60 min: workshops, beweging, inspiratielezingen",
      bijzonderheden: "",
      dresscode: "Sportief/casual",
      cateringWensen: "Gezonde snacks en drankjes elke dag beschikbaar",
      avTechniek: "",
      vrijeNotities: "Dag 1: beweging / Dag 2: voeding / Dag 3: mentaal welzijn / Dag 4: slaap / Dag 5: verbinding",
    },
    program: [],
    todos: [],
    budgetCategories: [
      { id: 1, name: "Gastsprekers & coaches", items: [] },
      { id: 2, name: "Catering (5 dagen)", items: [] },
      { id: 3, name: "Materialen & props", items: [] },
      { id: 4, name: "Overig", items: [] },
    ],
    timeline: [
      { id: 1, date: "21 sep", title: "Start Vitaliteitsweek", done: false, type: "user" },
      { id: 2, date: "25 sep", title: "Afsluiting Vitaliteitsweek", done: false, type: "user" },
    ],
    noteWindows: [],
  },

  {
    id: 4,
    name: "Alumni Borrel",
    date: "22 oktober 2025",
    startTime: "17:00",
    endTime: "21:00",
    location: "Kantoor",
    guests: 200,
    status: "concept",
    type: "Borrel",
    coverColor: "#e0924a",
    totalBudget: 9000,
    briefing: {
      concept: "",
      doelgroep: "200 alumni, oud-medewerkers en relaties",
      sfeerThema: "Nostalgie & verbinding",
      format: "Staande borrel, geen formeel programma",
      bijzonderheden: "Groot aantal gasten — ruimte op kantoor checken",
      dresscode: "Casual",
      cateringWensen: "Bites & drankenpakket voor 200 personen",
      avTechniek: "Achtergrondmuziek",
      vrijeNotities: "",
    },
    program: [],
    todos: [],
    budgetCategories: [
      { id: 1, name: "Catering & dranken", items: [] },
      { id: 2, name: "Decoratie", items: [] },
      { id: 3, name: "Personeel", items: [] },
      { id: 4, name: "Overig", items: [] },
    ],
    timeline: [
      { id: 1, date: "22 okt", title: "Alumni Borrel", done: false, type: "user" },
    ],
    noteWindows: [],
  },

  {
    id: 5,
    name: "Infrastructure Event J/S",
    date: "29 oktober 2025",
    startTime: "13:00",
    endTime: "18:00",
    location: "Haarlemmermeerstation, Haarlem",
    guests: 30,
    status: "concept",
    type: "Conferentie",
    coverColor: "#5c7a8c",
    totalBudget: 6000,
    briefing: {
      concept: "",
      doelgroep: "20–40 professionals uit de infrastructuursector",
      sfeerThema: "",
      format: "Presentaties + netwerksessie",
      bijzonderheden: "Locatie is historisch stationsgebouw — bijzondere sfeer",
      dresscode: "",
      cateringWensen: "",
      avTechniek: "",
      vrijeNotities: "",
    },
    program: [],
    todos: [],
    budgetCategories: [
      { id: 1, name: "Locatiehuur", items: [] },
      { id: 2, name: "Catering", items: [] },
      { id: 3, name: "AV & techniek", items: [] },
      { id: 4, name: "Sprekers", items: [] },
    ],
    timeline: [
      { id: 1, date: "29 okt", title: "Infrastructure Event J/S", done: false, type: "user" },
    ],
    noteWindows: [],
  },
];

// ─── Initial suppliers ──────────────────────────────────────────────────────

export const suppliers: Supplier[] = [
  {
    id: 1,
    name: "Westergasfabriek",
    category: "event-locaties",
    subcategories: ["Congres / conferentie", "Extern corporate", "Borrel / receptie"],
    address: "Pazzanistraat 33, 1014 DB Amsterdam",
    city: "Amsterdam",
    lat: 52.3863,
    lng: 4.8763,
    contact: { name: "Events team", phone: "020 586 0710", email: "events@westergasfabriek.nl" },
    priceIndication: "Vanaf €3.500 dagdeel",
    notes: "Uitstekende sfeerlocatie. Goede parkeergelegenheid. Meerdere zalen beschikbaar.",
  },
  {
    id: 2,
    name: "Het Scheepvaartmuseum",
    category: "event-locaties",
    subcategories: ["Kerstdiner", "Partnermeetings", "Extern corporate"],
    address: "Kattenburgerplein 1, 1018 KK Amsterdam",
    city: "Amsterdam",
    lat: 52.3727,
    lng: 4.9167,
    contact: { name: "Verhuur", phone: "020 523 2222", email: "verhuur@hetscheepvaartmuseum.nl" },
    priceIndication: "Op aanvraag",
    notes: "Unieke historische locatie. Prachtig voor kerstdiner en exclusieve corporate events.",
  },
  {
    id: 3,
    name: "Jachthaven Enkhuizen",
    category: "event-locaties",
    subcategories: ["Borrel / receptie", "Leisure kantoor"],
    address: "Buyskade 6, 1601 EA Enkhuizen",
    city: "Enkhuizen",
    lat: 52.7044,
    lng: 5.2953,
    contact: { name: "Havenmeester", phone: "0228 313 353", email: "info@jachthaven-enkhuizen.nl" },
    priceIndication: "€500–€1.500 dagdeel",
    notes: "Gebruikt voor Zeilevent Vastgoed 2025. Goede ervaring. Botenverhuur mogelijk via Enkhuizen Sailing.",
  },
  {
    id: 4,
    name: "Haarlemmermeerstation",
    category: "event-locaties",
    subcategories: ["Congres / conferentie", "Extern corporate", "Partnermeetings"],
    address: "Kruisweg 1227, 2132 NA Hoofddorp",
    city: "Hoofddorp",
    lat: 52.3038,
    lng: 4.7149,
    contact: { name: "Evenementen", phone: "023 558 1234", email: "events@haarlemmermeerstation.nl" },
    priceIndication: "€1.200–€3.000",
    notes: "Historisch stationsgebouw. Bijzondere atmosfeer. Gepland voor Infrastructure Event J/S.",
  },
  {
    id: 5,
    name: "Restaurant De Kas",
    category: "catering",
    subcategories: [],
    address: "Kamerlingh Onneslaan 3, 1097 DE Amsterdam",
    city: "Amsterdam",
    lat: 52.3617,
    lng: 4.9459,
    contact: { name: "Reserveringen", phone: "020 462 4562", email: "info@restaurantdekas.nl" },
    priceIndication: "€65–€110 p.p.",
    notes: "Groentegerichte keuken in een uniek kassenfeer. Ideaal voor exclusieve dinners.",
  },
  {
    id: 6,
    name: "Rooftop NDSM",
    category: "event-locaties",
    subcategories: ["Borrel / receptie", "Leisure kantoor"],
    address: "TT Neveritaweg 15, 1033 WB Amsterdam",
    city: "Amsterdam",
    lat: 52.4023,
    lng: 4.8977,
    contact: { name: "Verhuur", phone: "020 490 7773", email: "verhuur@ndsm.nl" },
    priceIndication: "€2.000–€4.500",
    notes: "Spectaculair uitzicht over Amsterdam. Regenplan altijd nodig. Goede DJ-faciliteiten.",
  },
];

export const defaultEventLocatieSubcats = [
  "Kerstdiner",
  "Partnermeetings",
  "Extern corporate",
  "Borrel / receptie",
  "Congres / conferentie",
  "Leisure kantoor",
];
